# This workflow runs all non-physical (unit) tests for the ECHONET Lite Python project
# It does NOT require a live ECHONET Lite device/server

name: Python CI (Unit Tests)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests (tests/)
        run: |
          python -m unittest discover -s tests -p 'test_*.py'
